### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by jarlave** [PokemonGo-Enhanced/Enhanced-Backend#12]
Hi,

I tried to install this, but it doesn't work.
I'm on Ubuntu 12.04

pythong
node-protobuf
libprotobuf
node-gyp
and node

is installed

Here my debug log: http://pastebin.com/RCL3YHfb

**Comment by rubenvereecken** [comment]
Not entirely sure when this one pops up, what version of Node are you running

**Comment by jarlave** [comment]
got it working now, i saw that it tried to use node 6.2.2, so I installed 6.3.1 again and now it works, now I need to get the frontend working ,because I have only a white screen (favicon works)
