### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by Cr4nkSt4r** [PokemonGo-Enhanced/Enhanced-Backend#14]
Solved

**Comment by panki27** [comment]
Try deleting your node_modules folder, then running `npm install` again.

**Comment by Cr4nkSt4r** [comment]
If I run `sudo npm run dev` problem 1 still exist, if I remove ={} the following error occours:
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

if I run `npm start`:

> Error: Cannot find module 'moment'


I deleted the folder and run `npm install` again

**Comment by panki27** [comment]
`Error: Cannot find module 'moment'`

You are missing a few modules, I had the same problem. You'll need to manually install them:

`npm install --save $modulename`

For me the ones missing were:
- moment
- change-case
- geodesy 
- haversine.

**Comment by Cr4nkSt4r** [comment]
Didn't work that much with npm, didn't know that I can install these modules that easy, thank you!

> user@machine:~/Enhanced-Backend$ npm start

> enhanced-backend@1.0.0 start /home/Enhanced-Backend
> cross-env NODE_ENV=production node ./lib/main.js

> [+++] PokemonGo MITM Proxy listening on 8080
> [!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device

`npm run dev` still don't work but who cares if stark work properly now.

Thank you for your help, fast and precise :+1:

**Comment by rubenvereecken** [comment]
Just to add to this conversation:

> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

I used to have this when I forgot to switch to my Node v6.3. Make sure to check with `node --version`! Otherwise, glad you got it working. And thanks for the help lads.

**Comment by Cr4nkSt4r** [comment]
As shown above, 6.3.1 was used.
I don't know why this strict error still exist in 6.3.1 :-/
Or if anything else is missing.
